packages:
  - acidify-core-js
  - acidify-docs
  - yogurt-scripting
  - yogurt-scripting/script-api
  - yogurt-scripting/script-example

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
