package org.ntqqrev.acidify.internal

import kotlinx.coroutines.CoroutineScope
import org.ntqqrev.acidify.common.android.AndroidAppInfo
import org.ntqqrev.acidify.common.android.AndroidSessionStore
import org.ntqqrev.acidify.common.android.AndroidSignProvider
import org.ntqqrev.acidify.internal.proto.system.SsoSecureInfo
import org.ntqqrev.acidify.internal.service.system.AndroidInfoSync
import org.ntqqrev.acidify.logging.Logger

internal class KuromeClient(
    val appInfo: AndroidAppInfo,
    val sessionStore: AndroidSessionStore,
    val signProvider: AndroidSignProvider,
    loggerFactory: (Any) -> Logger,
    scope: CoroutineScope,
) : AbstractClient(loggerFactory, scope) {
    override val os: String
        get() = appInfo.os

    override val uin: Long
        get() = sessionStore.uin

    override val uid: String
        get() = sessionStore.uid

    override val appId: Int
        get() = appInfo.appId

    override val subAppId: Int
        get() = appInfo.subAppId

    override val currentVersion: String
        get() = appInfo.currentVersion

    override val appClientVersion: Int
        get() = appInfo.appClientVersion

    override val a2: ByteArray
        get() = sessionStore.wloginSigs.a2

    override val d2: ByteArray
        get() = sessionStore.wloginSigs.d2

    override val d2Key: ByteArray
        get() = sessionStore.wloginSigs.d2Key

    override val guid: ByteArray
        get() = sessionStore.guid

    val signRequiredCommand = setOf(
        "trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access",
        "OidbSvcTcp.0x102a",
        "OidbSvcTrpcTcp.0xf88_1",
        "OidbSvcTrpcTcp.0x1105_1",
        "oidb_0xf7e_1",
        "OidbSvcTrpcTcp.0x92eb_0",
        "trpc.commercial.dataworks.UserActionReport_sso.SsoReport",
        "OidbSvcTrpcTcp.0xe37_1200",
        "OidbSvcTrpcTcp.0x55f_0",
        "MQUpdateSvc_com_qq_qzone_act.web.OidbSvcTrpcJsapiTcp.0x9377_0",
        "trpc.down.intercept.Intercept.SsoGetInterceptFile",
        "wtlogin.device_lock",
        "OidbSvcTrpcTcp.0x9409_15",
        "qidianservice.207",
        "SQQzoneSvc.addReply",
        "wtlogin.name2uin",
        "OidbSvcTrpcTcp.0x911a_22",
        "OidbSvcTrpcTcp.0xf67_5",
        "trpc.passwd.manager.PasswdManager.SetPasswd",
        "OidbSvc.0x8a1_0",
        "OidbSvcTrpcTcp.0x101e_2",
        "OidbSvcTrpcTcp.0xf67_1",
        "trpc.qpay.sso.web.Do",
        "OidbSvcTrpcTcp.0xf6e_1",
        "OidbSvcTrpcTcp.0x11ec_1",
        "SummaryCard.ReqSummaryCard",
        "OidbSvc.0x5eb_42261",
        "SQQzoneSvc.addComment",
        "trpc.msg.msg_svc.MsgService.SsoGetPeerSeq",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoComment",
        "SQQzoneSvc.like",
        "trpc.o3.ecdh_access.EcdhAccess.SsoSecureAccess",
        "OidbSvcTrpcTcp.0x1100_1",
        "SQQzoneSvc.Custom.getFacade",
        "trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey",
        "OidbSvcTrpcTcp.0xf57_1",
        "OidbSvcTrpcTcp.0x12a9_200",
        "wtlogin.exchange_emp",
        "OidbSvc.0x56c_6",
        "trpc.login.ecdh.EcdhService.SsoNTLoginRapidLogin",
        "RegPrxySvc.infoLogin",
        "OidbSvc.0x8a0_0",
        "QChannelSvr.trpc.qchannel.commwriter.ComWriter.PublishFeed",
        "trpc.login.ecdh.EcdhService.SsoNTLoginCheckThirdCode",
        "MQUpdateSvc_com_qq_ti.web.OidbSvcTrpcJsapiTcp.0x9172_0",
        "OidbSvcTrpcTcp.0x1258_1",
        "OidbSvcTrpcTcp.0x6d9_4",
        "trpc.lplan.feed_svr.StatusWrite.SsoPostStatus",
        "QChannelSvr.trpc.qchannel.commwriter.ComWriter.DoComment",
        "SQQzoneSvc.elaborateFeedReport",
        "OidbSvc.0x592_15",
        "OidbSvc.0x592_8",
        "QQStranger.InteractiveMsgSvr.SsoSendInterMsg",
        "ProfileService.GroupMngReq",
        "OidbSvcTrpcTcp.0xf89_1",
        "OidbSvc.0xe27",
        "ConnAuthSvr.get_app_info",
        "qidianservice.135",
        "OidbSvc.0x5eb_96",
        "OidbSvc.0x592_5",
        "trpc.group_pro.msgproxy.sendmsg",
        "oidb_0x43c_4",
        "OidbSvc.0xb3c_1",
        "trpc.msg.olpush.OlPushService.SsoPushAck",
        "QQStranger.login_svr.SsoLoginInfoReport",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoBarrage",
        "QQConnectLogin.get_promote_page",
        "OidbSvc.0xb77_46",
        "OidbSvc.0x5eb_22",
        "SQQzoneSvc.forward",
        "trpc.springfestival.redpacket.LuckyBag.SsoSubmitGrade",
        "trpc.msg.register_proxy.RegisterProxy.SsoInfoSync",
        "OidbSvc.0xb3c_6",
        "OidbSvc.0x89b_1",
        "wtlogin.login",
        "OidbSvcTrpcTcp.0x7c2_5",
        "oidb_0xcf3_0",
        "qidianservice.290",
        "trpc.qlive.word_svr.WordSvr.NewPublicChat",
        "wtlogin.register",
        "OidbSvcTrpcTcp.0xf57_9",
        "MQUpdateSvc_com_qq_ti.web.OidbSvcTrpcJsapiTcp.0x9044_0",
        "friendlist.GetMultiTroopInfoReq",
        "StatSvc.GetOnlineStatus",
        "OidbSvcTrpcTcp.0x9560_1",
        "OidbSvcTrpcTcp.0x89a_0",
        "OidbSvcTrpcTcp.0x10db_1",
        "OidbSvc.0x9fa",
        "OidbSvcTrpcTcp.0xe37_800",
        "qidianservice.269",
        "OidbSvcTrpcTcp.0xf65_1",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.PublishFeed",
        "OidbSvcTrpcTcp.0x11ea_200",
        "OidbSvcTrpcTcp.0x9127_1",
        "QQStranger.FeedPlazaSvr.SsoFeedPublish",
        "OidbSvc.0xb3c_get_by_id",
        "trpc.login.ecdh.EcdhService.SsoQRLoginGenQr",
        "OidbSvc.0x592_10",
        "oidb_0xd9c_11",
        "wtlogin_device.login",
        "OidbSvcTrpcTcp.0xfe7_4",
        "OidbSvcTrpcTcp.0xfe7_3",
        "trpc.qpay.red_pack_skin.Skin.SsoAddSkin",
        "OidbSvcTrpcTcp.0x101e_1",
        "OidbSvcTrpcTcp.0xfe1_8",
        "MsgProxy.SendMsg",
        "OidbSvcTrpcTcp.0x899_1",
        "trpc.lplan.user_manager_svr.User.SsoSetProfile",
        "trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginUnusualDevice",
        "QChannelSvr.trpc.qchannel.commwriter.ComWriter.DoReply",
        "OidbSvc.0x5eb_43",
        "trpc.login.ecdh.EcdhService.SsoKeyExchange",
        "trpc.passwd.manager.PasswdManager.VerifyPasswd",
        "OidbSvc.0xb3c_update_5",
        "OidbSvc.0x592_17",
        "trpc.msg.register_proxy.RegisterProxy.PushParams",
        "WalletGestureSvc.GetSignV2",
        "OidbSvcTrpcTcp.0x9409_14",
        "friendlist.ModifyGroupInfoReq",
        "OidbSvc.oidb_0x758",
        "QQConnectLogin.submit_promote_page_emp",
        "OidbSvc.0x8a8",
        "OidbSvcTrpcTcp.0x1107_1",
        "QQConnectLogin.pre_auth_emp",
        "SQQzoneSvc.getProfile",
        "ProfileService.getGroupInfoReq",
        "OidbSvcTrpcTcp.0x8a1_7",
        "OidbSvc.0xb77_34",
        "QQConnectLogin.auth",
        "OidbSvcTrpcTcp.0x8fc_3",
        "ConnAuthSvr.get_auth_api_list_emp",
        "QQConnectLogin.auth_emp",
        "trpc.o3.report.Report.SsoReport",
        "ConnAuthSvr.get_auth_api_list",
        "OidbSvc.0xb77_9",
        "PushService.settoken",
        "trpc.lplan.feed_svr.StatusWrite.SsoComment",
        "trpc.lplan.feed_svr.StatusWrite.SsoReply",
        "trpc.lplan.like_svr.Like.SsoDoLike",
        "trpc.login.ecdh.EcdhService.SsoNTLoginAuthNewDevice",
        "miniapp.trpc.minigame.sdk_qgroup_svr.sdk_qgroup_svr.JoinGroup",
        "QQStranger.FeedSvr.SsoFeedPublish",
        "OidbSvcTrpcTcp.0x9176_1",
        "OidbSvc.0x592_6",
        "QQStranger.UserInfo.SsoGetMiniUserInfo",
        "QQConnectLogin.get_promote_page_emp",
        "LightAppSvc.mini_app_userapp.GetDropdownAppList",
        "OidbSvc.0x8a1_7",
        "OidbSvc.0x5d0_1",
        "OidbSvc.0xb3c_get_undone",
        "OidbSvc.0x758_0",
        "OidbSvcTrpcTcp.0x10ed_1",
        "OidbSvc.0x59f",
        "OidbSvc.0xb3c_get_done",
        "OidbSvc.0xb3c_update",
        "OidbSvc.0xc26_0",
        "SQQzoneSvc.GetCate",
        "PttStore.GroupPttDown",
        "OidbSvc.0xb3c_delete",
        "OidbSvc.0xb3c_share",
        "FeedCloudSvr.trpc.videocircle.circleprofile.CircleProfile.SetProfile",
        "trpc.login.ecdh.EcdhService.SsoNTLoginRefreshA2",
        "OidbSvc.0xb3c_get_done_count",
        "OidbSvc.0x592_19",
        "OidbSvcTrpcTcp.0x112e_1",
        "OidbSvc.0xb3c",
        "OidbSvc.0xb3c_2",
        "trpc.qlive.relationchain_svr.RelationchainSvr.Follow",
        "OidbSvc.0xb3c_5",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoReply",
        "OidbSvc.0xb3c_4",
        "trpc.qqstranger.common_proxy.CommonProxy.SsoHandle",
        "QQStranger.UserInfo.SsoSetMiniUserInfo",
        "OidbSvc.0x4ff_9",
        "OidbSvc.0xef0_1",
        "OidbSvc.0xb3c_7",
        "OidbSvc.0x4ff_9_IMCore",
        "OidbSvcTrpcTcp.0x1250_0",
        "OidbSvcTrpcTcp.0xa80_1",
        "OidbSvcTrpcTcp.0xfe4_2",
        "OidbSvc.0x89a_0",
        "OidbSvc.0xb3c_8",
        "OidbSvcTrpcTcp.0x930e_0",
        "trpc.login.ecdh.EcdhService.SsoNTLoginCheckSms",
        "OidbSvcTrpcTcp.0x125b_500",
        "friendlist.GetLastLoginInfoReq",
        "OidbSvc.0x592",
        "ConnAuthSvr.sdk_auth_api",
        "OidbSvcTrpcTcp.0x955f_1",
        "OidbSvc.0xcd5",
        "oidb_0xcf4_0",
        "OidbSvc.0x592_2",
        "OidbSvcTrpcTcp.0xf65_10",
        "OidbSvcTrpcTcp.0x92e4_0",
        "ConnAuthSvr.fast_qq_login",
        "OidbSvc.0x758",
        "trpc.QQService.CommonLogic.StatusService.SsoGetLikeList",
        "trpc.login.ecdh.EcdhService.SsoNTLoginCheckGateWayCode",
        "OidbSvc.0x592_9",
        "OidbSvcTrpcTcp.0x9078_1",
        "oidb_0x9072_0",
        "OidbSvc.0x592_11",
        "OidbSvc.0x592_12",
        "wtlogin_device.tran_sim_emp",
        "StatSvc.SetStatusFromClient",
        "OidbSvcTrpcTcp.0x9559_0",
        "OidbSvc.0x592_16",
        "OidbSvc.0xe3e",
        "OidbSvc.0x8ba",
        "OidbSvc.0xb77_48",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetCommentList",
        "account.RequestQueryQQMobileContactsV3",
        "OidbSvcTrpcTcp.0x758_1",
        "FeedCloudSvr.trpc.circlesearch.exhibition.ExhibitionSvr.ExhibitionSuggestion",
        "WalletGestureSvc.GetPassword",
        "OidbSvc.0x592_3",
        "OidbSvcTrpcTcp.0xf55_1",
        "WalletGestureSvc.SetPassword",
        "friendlist.GetTroopMemberList",
        "OidbSvcTrpcTcp.0xfd4_1",
        "OidbSvcTrpcTcp.0xfa5_1",
        "OidbSvcTrpcTcp.0x787_1",
        "SQQzoneSvc.getUndealCount",
        "trpc.login.ecdh.EcdhService.SsoOIDB0x916a",
        "OidbSvc.0x8a4",
        "OidbSvc.0x7a2_0",
        "OidbSvcTrpcTcp.0x10c8_2",
        "trpc.qpay.encryptedtransfer.Encryption.SsoUINEncrypt",
        "oidb_0xeb1_1",
        "oidb_0xdc2_34",
        "friendlist.GetSimpleOnlineFriendInfoReq",
        "OidbSvcTrpcTcp.0x105b_1",
        "trpc.qlive.qlive_proxy_svr.TrpcProxy.*",
        "OidbSvc.0x592_4",
        "OidbSvcTrpcTcp.0xfe1_2",
        "SQQzoneSvc.publishmood",
        "trpc.login.ecdh.EcdhService.SsoNTLoginGetSaltList",
        "ResourceConfig.GetResourceReq",
        "trpc.down.joint_operation_game_intercept.JointOperationGameIntercept.SsoCheck",
        "friendlist.getTroopMemberList",
        "OidbSvc.0xb3c_3",
        "trpc.qpay.midas_order.Order.SsoMakeOrder",
        "OidbSvcTrpcTcp.0x116c_1",
        "OidbSvcTrpcTcp.0x1017_1",
        "trpc.down.intercept.Intercept.SsoGetDownloadTips",
        "OidbSvcTrpcTcp.0x911a_19",
        "OidbSvcTrpcTcp.0x10e4_1",
        "LightAppSvc.mini_app_cloudstorage.GetUserCloudStorage",
        "QChannelSvr.trpc.qchannel.commreader.ComReader.BatchGetFeedDetail",
        "CertifiedAccountSvc.certified_account_read.GetFollowList",
        "trpc.login.ecdh.EcdhService.SsoOIDB0x916b",
        "SecuritySvc.GetConfig",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoFollow",
        "trpc.down.joint_operation_game_intercept.JointOperationGameIntercept.SsoQueryConfig",
        "OidbSvcTrpcTcp.0x930d_0",
        "OidbSvc.0x6d7_0",
        "OidbSvcTrpcTcp.0x9689_1",
        "trpc.login.ecdh.EcdhService.SsoQRLoginScanQr",
        "SQQzoneSvc.getProfileFeeds",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoLike",
        "OidbSvcTrpcTcp.0xcd5",
        "trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish",
        "ProfileService.ReqBatchProcess",
        "trpc.login.ecdh.EcdhService.SsoNTLoginCheckA1List",
        "trpc.login.ecdh.EcdhService.SsoNTLoginRefreshTicket",
        "OidbSvc.0x6d6_2",
        "ProfileService.Pb.ReqSystemMsgAction.Group",
        "trpc.login.ecdh.EcdhService.SsoNTLoginOptimusLogin",
        "FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoPush",
        "group_member_statistic.get_group_member_statistic",
        "OidbSvcTrpcTcp.0x116d_1",
        "trpc.qq_new_tech.status_svc.StatusService.SsoHeartBeat",
        "OidbSvc.0x787_0",
        "ConnAuthSvr.get_app_info_emp",
        "SQQzoneSvc.getVisitorNotify",
        "gcbindgroupsso.get_appid",
        "trpc.login.ecdh.EcdhService.SsoNTLoginGetSms",
        "wtlogin.qrlogin",
        "OidbSvc.0x592_13",
        "MessageSvc.PbSendMsg",
        "friendlist.GetTroopListReqV2",
        "trpc.login.ecdh.EcdhService.SsoOIDB0x916c",
        "trpc.login.ecdh.EcdhService.SsoOIDB0x916d",
        "OidbSvcTrpcTcp.0x11c4_100",
        "trpc.login.ecdh.EcdhService.SsoQRLoginAuthQr",
        "OidbSvcTrpcTcp.0xf57_106",
        "trpc.login.ecdh.EcdhService.SsoQRLoginRejectQr",
        "OidbSvc.0xdc2_9",
        "OidbSvc.0xd69",
        "OidbSvc.0xb3c_add",
        "OidbSvc.0xdc2_34",
        "MQUpdateSvc_com_qq_ti.web.OidbSvcTrpcJsapiTcp.0x9047_0",
        "OidbSvcTrpcTcp.0x93d7_1",
        "OidbSvcTrpcTcp.0x91b6_1",
        "OidbSvcTRPCTcp.0x758_1",
        "OidbSvcTrpcTcp.0x92e3_0",
        "SQQzoneSvc.photo",
        "trpc.qmeta.mob_proxy_svr.MobProxy.SsoHandle",
        "OidbSvc.0xc33_42220",
        "OidbSvcTRPCTcp.0xf67_1",
        "OidbSvcTrpcTcp.0xb77_57",
        "OidbSvcTrpcTcp.0x9076_1",
        "SQQzoneSvc.getPhotoWall",
        "OidbSvcTrpcTcp.0x10f4_1",
        "friendlist.AddFriendReq",
        "OidbSvcTcp.0xef0_1",
        "OidbSvcTrpcTcp.0xf5b_1",
        "VisitorSvc.ReqFavorite",
        "OidbSvcTrpcTcp.0x10c8_1",
        "OidbSvcTrpcTcp.0x88d_0",
        "OidbSvcTrpcTcp.0x9409_7",
        "OidbSvcTrpcTcp.0x9409_10",
        "OidbSvcTrpcTcp.0x9409_11",
        "OidbSvcTrpcTcp.0x962a_1",
        "ConnAuthSvr.sdk_auth_api_emp",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetRelationGroupList",
        "OidbSvc.0x5eb_42073",
        "OidbSvcTrpcTcp.0x9409_12",
        "OidbSvcTrpcTcp.0x899_9",
        "oidb_0xe61_1",
        "OidbSvc.0x88d_1_2",
        "OidbSvc.0x592_1",
        "OidbSvcTrpcTcp.0x126e_200",
        "OidbSvcTrpcTcp.0x9409_13",
        "OidbSvcTrpcTcp.0x9409_16",
        "OidbSvcTrpcTcp.0x9409_18",
        "OidbSvc.0x592_7",
        "ProfileService.SimpleInfo",
        "OidbSvcTrpcTcp.0x101b_1",
        "SQQzoneSvc.getMainPage",
        "trpc.login.ecdh.EcdhService.SsoNTLoginEasyLogin",
        "OidbSvc.0x6d6_0",
        "OidbSvcTrpcTcp.0x12b1_0",
        "OidbSvcTrpcTcp.0x9079_1",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetMainPageCommData",
        "OidbSvcTrpcTcp.0x1277_0",
        "OidbSvcTrpcTcp.0x123c_1",
        "OidbSvc.0x5eb_common",
        "ProfileService.GetSimpleInfo",
        "trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLogin",
        "trpc.qq_new_tech.status_svc.StatusService.Register",
        "OidbSvc.0x6de",
        "OidbSvc.0x592_18",
        "OidbSvc.0x88d_0",
        "StatSvc.GetDevLoginInfo",
        "OidbSvcTrpcTcp.0xf59_1",
        "OidbSvcTrpcTcp.0x9144_1",
        "OidbSvcTrpcTcp.0x9a2_8",
        "trpc.group_pro.synclogic.SyncLogic.SyncFirstView",
        "StatSvc.SimpleGet",
        "ProfileService.Pb.ReqSystemMsgNew.Group",
        "OidbSvcTrpcTcp.0x1092_0",
        "OidbSvcTrpcTcp.0x102a_1",
        "OidbSvcTrpcTcp.0x88d_14",
        "trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg",
        "trpc.qqva.vipdata.Vipdata.SsoGetUserData",
        "oidb_0xfd4_1",
        "QQConnectLogin.submit_promote_page",
        "oidb_0xe37_800",
        "OidbSvcTrpcTcp.0x1102_1",
        "oidb_0x9045_1",
        "oidb_0x7a2_0",
        "oidb_0x42e_3",
        "friendlist.GetTroopAppointRemarkReq",
        "trpc.lplan.map_svr.Map.SsoReportLocation",
        "oidb_0x7c4_0",
        "OidbSvcTrpcTcp.0xfe5_2",
        "wtlogin.log_report",
        "gcbindgroupsso.unbind_group",
        "friendlist.GetFriendListReq",
        "VisitorSvc.ReqDeleteVisitorRecord",
        "SQQzoneSvc.get_all_feedsphoto_ex",
        "StatSvc.register",
        "OidbSvc.0xc6b",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetBusiInfo",
        "GameCenterMsg.GetUserInfo",
        "MessageSvc.PbGetMsg",
        "SQQzoneSvc.getPhotoComment",
        "oidb_0x7df_3",
        "SQQzoneSvc.getActiveFeeds",
        "trpc.metaverse.mob_proxy_svr.MobProxy.SsoHandle",
        "SQQzoneSvc.preGetPassiveFeeds",
        "SQQzoneSvc.getAIONewestFeeds",
        "ResourceConfig.ClientReq",
        "friendlist.getFriendGroupList",
        "OidbSvcTrpcTcp.0x102a_0",
        "QQStranger.UserInfo.SsoBatchGetMiniUserInfo",
        "PbMessageSvc.PbUnReadMsgSeq",
        "OidbSvc_device.0x9f5",
        "OidbSvcTrpcTcp.0xf5d_1",
        "OidbSvcTrpcTcp.0xe37_1700",
        "OidbSvcTrpcTcp.0x972_6",
        "trpc.g_qqrtc.qq_mav_room_state_read.GetRoomState.SsoGetInfoByUin",
        "OidbSvc.0x758_1",
        "OidbSvcTrpcTcp.0x901f_1",
        "OidbSvc.0x5eb_99",
        "OidbSvcTrpcTcp.0x899_0",
        "OidbSvc.0x6d9_4",
        "OidbSvc.0x787_1",
        "OidbSvcTrpcTcp.0x88d_111",
        "friendlist.addFriend",
        "OidbSvcTrpcTcp.0x6d9_2",
        "OidbSvcTrpcTcp.0x6d6_3",
        "OidbSvcTrpcTcp.0x127a_0",
        "RegPrxySvc.infoSync",
        "OidbSvcTrpcTcp.0x121e_0",
        "OidbSvcTrpcTcp.0x1130_1",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetFeedList",
        "OidbSvc.0xe61",
        "OidbSvcTrpcTcp.0x6d6_2",
        "OidbSvcTrpcTcp.0x92d5_0",
        "trpc.login.ecdh.EcdhService.SsoQRLoginCancleQr",
        "OidbSvc.0x480_9",
        "OidbSvc.0x53c_2",
        "SQQzoneSvc.shuoshuo",
        "OidbSvcTrpcTcp.0x126d_200",
        "OidbSvcTrpcTcp.0x1225_0",
        "OidbSvcTrpcTcp.0xfc9_1",
        "OidbSvcTrpcTcp.0x1224_0",
        "QQConnectLogin.pre_auth",
        "OidbSvc.0x6d6_3",
        "OidbSvcTrpcTcp.0x11e9_200",
        "wtlogin.trans_emp",
        "OidbSvc.0x852_48",
        "OidbSvc.0xbcb",
        "OidbSvc.0x42d",
        "OidbSvc.0x515_2",
        "OidbSvcTrpcTcp.0x11c5_200",
        "OidbSvcTrpcTcp.0x11c4_200",
        "trpc.qqhb.qqhb_proxy.Handler.sso_handle",
        "OidbSvc.0x852_35",
        "OidbSvcTrpcTcp.0x1194_1",
        "OidbSvcTrpcTcp.0x10c0_1",
        "OidbSvc.0x88d_7",
        "OidbSvcTrpcTcp.0x110d_1",
        "OidbSvcTrpcTcp.0xfe1",
        "OidbSvcTrpcTcp.0x902e_1",
        "OidbSvcTrpcTcp.0x10c0_2",
        "QSec.AVEng",
        "HttpConn.0x6ff_501",
        "group_member_card.get_group_member_card_info",
        "OidbSvc.0x570_8",
        "OidbSvc.0xe63_1",
        "OidbSvcTrpcTcp.0x8f9_14",
        "OidbSvc.0x587_123",
        "OidbSvc.0x899_9",
        "OidbSvc.0x7df_3",
        "trpc.qq_new_tech.status_svc.StatusService.UnRegister",
        "OidbSvcTrpcTcp.0x5cf_11",
        "OidbSvc.0x899_0",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetReplyList",
        "OidbSvc.0x58b",
        "OidbSvcTrpcTcp.0x9a2_12",
        "OidbSvcTrpcTcp.0xfe7_2",
        "oidb_0x5d0_1",
        "OidbSvc.0xf7e_1",
        "OidbSvcTrpcTcp.0x644_1",
        "oidb_0x43c_5",
        "OidbSvc.0xbe8",
        "trpc.lplan.user_manager_svr.User.SsoLogin",
        "MessageSvc.PbGetRoamMsg",
        "oidb_0xe8c_0",
        "OidbSvcTrpcTcp.0x10d8_1",
        "OidbSvcTrpcTcp.0xe37_700",
        "OidbSvc.0x587_normalNightSet",
        "OidbSvcTrpcTcp.0xf5d_11",
        "QQRTCSvc.RoomManager-GetRoomInfo",
        "PubAccountSvc.get_follow_list",
        "OidbSvc.0x88d_1",
        "oidb_0x5d6_21",
        "trpc.gc_indust.device_report.SsoHome.SsoHomeReport",
        "oidb_0x5d6_19",
        "OidbSvc.0x8f1",
        "OidbSvcTrpcTcp.0x11e9_100",
        "OidbSvc.0xe72",
        "OidbSvc.0x5eb_ForTheme",
        "OidbSvc.0x787_11",
        "NowSummaryCard.NearbyMiniCardReq",
        "OidbSvc.0x5eb_15",
        "OidbSvc.0x5eb_cn_switch",
        "friendlist.GetTroopMemberListReq",
        "SQQzoneSvc.get",
        "OidbSvcTcp.0x88d_0",
        "OidbSvcTrpcTcp.0x11c5_100",
        "SQQzoneSvc.mobileqboss.get",
        "qzoneh5.h5.wnshtml",
        "OidbSvc.0x580_1",
        "SsoSnsSession.Cmd0x3_SubCmd0x1_FuncGetBlockList",
        "OidbSvcTrpcTcp.0x1262_19",
        "OidbSvc.0x42d_4",
        "OidbSvc.0xbbb",
        "OidbSvc_device.0x633",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetRerankedFeedList",
        "OidbSvc.0xcdd",
        "OidbSvcTrpcTcp.0xf59_2",
        "MessageSvc.PbGetGroupMsg",
        "MessageSvc.PbBindUinGetMsg",
        "AvatarInfoSvr.QQHeadUrlReq",
        "ConfigPushSvc.PushResp",
        "OidbSvc.0x480_9_IMCore",
        "OidbSvcTcp.0x88d_1",
        "OidbSvcTrpcTcp.0x1289_1",
        "LightAppSvc.mini_app_privacy.GetPrivacyInfo",
        "oidb_0xe37_1200",
        "OidbSvcTrpcTcp.0x9124_0",
        "FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetMainPageBasicData",
        "OidbSvcTrpcTcp.0xaf6_0",
        "IncreaseURLSvr.QQHeadUrlReq"
    )

    override suspend fun getSsoSecureInfo(cmd: String, seq: Int, src: ByteArray): SsoSecureInfo? {
        return if (signRequiredCommand.contains(cmd)) {
            signProvider.sign(
                uin = uin,
                cmd = cmd,
                seq = seq,
                buffer = src,
                guid = guid.toHexString(),
                version = appInfo.ptVersion,
                qua = appInfo.qua,
            ).let {
                SsoSecureInfo(
                    sign = it.sign,
                    token = it.token,
                    extra = it.extra,
                )
            }
        } else {
            null
        }
    }

    override suspend fun sendOnlinePacket() = callService(AndroidInfoSync)
}